"""Core package for the new novel agent workbench."""

from .application_service import WorkbenchApplicationService
from .audit import AuditFinding, audit_project
from .drafts import (
    DraftCommitResult,
    DraftGenerationError,
    DraftGenerationRequest,
    DraftGenerationResult,
    DraftGenerationService,
)
from .providers import (
    ModelRoleConfig,
    MockProviderClient,
    ProviderAdapterInfo,
    ProviderConfigError,
    ProviderClient,
    ProviderConnectionResult,
    ProviderDryRunResult,
    ProviderError,
    ProviderRequest,
    ProviderResponse,
    configure_provider_role,
    create_provider_client,
    fake_test_model_role,
    generate_with_provider,
    get_model_role_config,
    list_provider_adapters,
    provider_dry_run,
    provider_status,
    read_provider_call_log,
    resolve_project_secret,
    set_project_secret,
    set_model_role_config,
)
from .project_state import public_project_state
from .storage import InvalidProjectIdError, ProjectLockError, ProjectRegistry, ProjectStore, StorageError

__all__ = [
    "InvalidProjectIdError",
    "ModelRoleConfig",
    "MockProviderClient",
    "ProviderAdapterInfo",
    "ProviderConfigError",
    "ProviderClient",
    "ProviderConnectionResult",
    "ProviderDryRunResult",
    "ProviderError",
    "ProviderRequest",
    "ProviderResponse",
    "ProjectLockError",
    "ProjectRegistry",
    "ProjectStore",
    "StorageError",
    "WorkbenchApplicationService",
    "AuditFinding",
    "audit_project",
    "configure_provider_role",
    "create_provider_client",
    "DraftCommitResult",
    "DraftGenerationError",
    "DraftGenerationRequest",
    "DraftGenerationResult",
    "DraftGenerationService",
    "fake_test_model_role",
    "generate_with_provider",
    "get_model_role_config",
    "list_provider_adapters",
    "provider_dry_run",
    "provider_status",
    "read_provider_call_log",
    "resolve_project_secret",
    "public_project_state",
    "set_project_secret",
    "set_model_role_config",
]
