"""Core package for the new novel agent workbench."""

from .application_service import WorkbenchApplicationService
from .audit import AuditFinding, audit_project
from .chapters import ChapterWorkflowEntry, ChapterWorkflowError, ChapterWorkflowService
from .context_assembler import ContextAssemblerService, ContextAssemblyDryRunResult
from .context_previews import ContextUpdatePreviewError, ContextUpdatePreviewResult, ContextUpdatePreviewService
from .context_queue import ContextUpdateQueueError, ContextUpdateQueueResult, ContextUpdateQueueService
from .drafts import (
    DraftCommitResult,
    DraftGenerationError,
    DraftGenerationRequest,
    DraftGenerationResult,
    DraftGenerationService,
)
from .formal_context import FormalContextPlanError, FormalContextPlanResult, FormalContextPlanService
from .formal_context_tasks import (
    FormalContextTaskQueueError,
    FormalContextTaskQueueResult,
    FormalContextTaskQueueService,
)
from .memory_apply_preview import (
    MemoryApplyCommitResult,
    MemoryApplyPreviewError,
    MemoryApplyPreviewResult,
    MemoryApplyPreviewService,
)
from .providers import (
    CHUTES_PROVIDER_ID,
    ModelRoleConfig,
    MockProviderClient,
    ProviderAdapterInfo,
    ProviderConfigError,
    ProviderClient,
    ProviderConnectionResult,
    ProviderDryRunResult,
    ProviderError,
    ProviderRequest,
    ProviderRealTestResult,
    ProviderResponse,
    configure_provider_role,
    create_provider_client,
    fake_test_model_role,
    generate_with_provider,
    get_model_role_config,
    list_provider_adapters,
    provider_dry_run,
    provider_real_test,
    provider_status,
    read_provider_call_log,
    resolve_project_secret,
    set_real_generation_enabled,
    set_project_secret,
    set_model_role_config,
)
from .project_state import public_project_state
from .runbooks import ChutesGenerateOnceRequest, chutes_generate_once
from .reviews import DraftReviewError, DraftReviewResult, DraftReviewService, ReviewDecisionResult
from .revision_candidates import (
    RevisionCandidateComparison,
    RevisionCandidateError,
    RevisionCandidateService,
    RevisionCandidateSummary,
)
from .revisions import RevisionRequestError, RevisionRequestResult, RevisionRequestService
from .storage import InvalidProjectIdError, ProjectLockError, ProjectRegistry, ProjectStore, StorageError

__all__ = [
    "InvalidProjectIdError",
    "ModelRoleConfig",
    "MockProviderClient",
    "ProviderAdapterInfo",
    "ProviderConfigError",
    "ProviderClient",
    "ProviderConnectionResult",
    "ProviderDryRunResult",
    "ProviderError",
    "ProviderRequest",
    "ProviderRealTestResult",
    "ProviderResponse",
    "ProjectLockError",
    "ProjectRegistry",
    "ProjectStore",
    "StorageError",
    "WorkbenchApplicationService",
    "AuditFinding",
    "CHUTES_PROVIDER_ID",
    "ChutesGenerateOnceRequest",
    "ChapterWorkflowEntry",
    "ChapterWorkflowError",
    "ChapterWorkflowService",
    "ContextAssemblerService",
    "ContextAssemblyDryRunResult",
    "ContextUpdateQueueError",
    "ContextUpdateQueueResult",
    "ContextUpdateQueueService",
    "ContextUpdatePreviewError",
    "ContextUpdatePreviewResult",
    "ContextUpdatePreviewService",
    "audit_project",
    "chutes_generate_once",
    "configure_provider_role",
    "create_provider_client",
    "DraftCommitResult",
    "DraftGenerationError",
    "DraftGenerationRequest",
    "DraftGenerationResult",
    "DraftGenerationService",
    "DraftReviewError",
    "DraftReviewResult",
    "DraftReviewService",
    "FormalContextPlanError",
    "FormalContextPlanResult",
    "FormalContextPlanService",
    "FormalContextTaskQueueError",
    "FormalContextTaskQueueResult",
    "FormalContextTaskQueueService",
    "MemoryApplyPreviewError",
    "MemoryApplyPreviewResult",
    "MemoryApplyCommitResult",
    "MemoryApplyPreviewService",
    "ReviewDecisionResult",
    "RevisionCandidateComparison",
    "RevisionCandidateError",
    "RevisionCandidateService",
    "RevisionCandidateSummary",
    "RevisionRequestError",
    "RevisionRequestResult",
    "RevisionRequestService",
    "fake_test_model_role",
    "generate_with_provider",
    "get_model_role_config",
    "list_provider_adapters",
    "provider_dry_run",
    "provider_real_test",
    "provider_status",
    "read_provider_call_log",
    "resolve_project_secret",
    "public_project_state",
    "set_real_generation_enabled",
    "set_project_secret",
    "set_model_role_config",
]
