"""Core package for the new novel agent workbench."""

from .application_service import WorkbenchApplicationService
from .audit import AuditFinding, audit_project
from .chapters import ChapterWorkflowEntry, ChapterWorkflowError, ChapterWorkflowService
from .context_assembler import (
    ContextAssemblerService,
    ContextAssemblyDryRunResult,
    ContextPackagePreviewResult,
    PromptRenderDryRunResult,
)
from .context_previews import ContextUpdatePreviewError, ContextUpdatePreviewResult, ContextUpdatePreviewService
from .context_queue import ContextUpdateQueueError, ContextUpdateQueueResult, ContextUpdateQueueService
from .corpus_boundaries import CorpusBoundaryError, CorpusBoundaryResult, CorpusBoundaryService
from .corpus_profiler import CorpusProfilerError, CorpusProfileResult, profile_corpus
from .corpus_profiles import CorpusProfileArtifactError, CorpusProfileArtifactResult, CorpusProfileArtifactService
from .corpus_samples import CorpusSampleError, CorpusSampleResult, CorpusSampleService
from .drafts import (
    DraftCommitResult,
    DraftGenerationError,
    DraftGenerationRequest,
    DraftGenerationResult,
    DraftGenerationService,
)
from .formal_context import FormalContextPlanError, FormalContextPlanResult, FormalContextPlanService
from .formal_context_tasks import (
    FormalContextTaskQueueError,
    FormalContextTaskQueueResult,
    FormalContextTaskQueueService,
)
from .manual_rewrite import (
    ManualRewriteDraftSubmissionResult,
    ManualRewriteTaskError,
    ManualRewriteTaskResult,
    ManualRewriteTaskService,
    ManualRewriteTaskStatusResult,
)
from .manual_rewrite_comparison import (
    ManualRewriteComparisonDecisionResult,
    ManualRewriteComparisonError,
    ManualRewriteComparisonResult,
    ManualRewriteComparisonService,
)
from .memory_apply_preview import (
    MemoryApplyCommitResult,
    MemoryApplyPreviewError,
    MemoryApplyPreviewResult,
    MemoryApplyPreviewService,
)
from .memory_bank import MemoryBankError, MemoryBankLifecycleResult, MemoryBankService, MemoryBankUpdateResult
from .providers import (
    CHUTES_PROVIDER_ID,
    ModelRoleConfig,
    MockProviderClient,
    ProviderAdapterInfo,
    ProviderConfigError,
    ProviderClient,
    ProviderConnectionResult,
    ProviderDryRunResult,
    ProviderError,
    ProviderRequest,
    ProviderRealTestResult,
    ProviderResponse,
    configure_provider_role,
    create_provider_client,
    fake_test_model_role,
    generate_with_provider,
    get_model_role_config,
    list_provider_adapters,
    provider_dry_run,
    provider_real_test,
    provider_status,
    read_provider_call_log,
    resolve_project_secret,
    set_real_generation_enabled,
    set_project_secret,
    set_model_role_config,
)
from .project_state import public_project_state
from .publication import PrepublishFinding, prepublish_check
from .runbooks import ChutesGenerateOnceRequest, chutes_generate_once
from .reviews import DraftReviewError, DraftReviewResult, DraftReviewService, ReviewDecisionResult
from .revision_candidates import (
    RevisionCandidateComparison,
    RevisionCandidateError,
    RevisionCandidateService,
    RevisionCandidateSummary,
)
from .revisions import RevisionRequestError, RevisionRequestResult, RevisionRequestService
from .self_style import (
    DraftStyleCheckResult,
    DraftStyleSuggestionResult,
    SelfStyleBaselineError,
    SelfStyleBaselineResult,
    SelfStyleBaselineService,
    StyleSuggestionDecisionResult,
)
from .storage import InvalidProjectIdError, ProjectLockError, ProjectRegistry, ProjectStore, StorageError

__all__ = [
    "InvalidProjectIdError",
    "ModelRoleConfig",
    "MockProviderClient",
    "ProviderAdapterInfo",
    "ProviderConfigError",
    "ProviderClient",
    "ProviderConnectionResult",
    "ProviderDryRunResult",
    "ProviderError",
    "ProviderRequest",
    "ProviderRealTestResult",
    "ProviderResponse",
    "ProjectLockError",
    "ProjectRegistry",
    "ProjectStore",
    "DraftStyleCheckResult",
    "DraftStyleSuggestionResult",
    "StyleSuggestionDecisionResult",
    "SelfStyleBaselineError",
    "SelfStyleBaselineResult",
    "SelfStyleBaselineService",
    "StorageError",
    "WorkbenchApplicationService",
    "AuditFinding",
    "CHUTES_PROVIDER_ID",
    "ChutesGenerateOnceRequest",
    "ChapterWorkflowEntry",
    "ChapterWorkflowError",
    "ChapterWorkflowService",
    "ContextAssemblerService",
    "ContextAssemblyDryRunResult",
    "ContextPackagePreviewResult",
    "PromptRenderDryRunResult",
    "PrepublishFinding",
    "ContextUpdateQueueError",
    "ContextUpdateQueueResult",
    "ContextUpdateQueueService",
    "ContextUpdatePreviewError",
    "ContextUpdatePreviewResult",
    "ContextUpdatePreviewService",
    "CorpusProfilerError",
    "CorpusProfileResult",
    "CorpusBoundaryError",
    "CorpusBoundaryResult",
    "CorpusBoundaryService",
    "CorpusProfileArtifactError",
    "CorpusProfileArtifactResult",
    "CorpusProfileArtifactService",
    "CorpusSampleError",
    "CorpusSampleResult",
    "CorpusSampleService",
    "audit_project",
    "chutes_generate_once",
    "configure_provider_role",
    "create_provider_client",
    "DraftCommitResult",
    "DraftGenerationError",
    "DraftGenerationRequest",
    "DraftGenerationResult",
    "DraftGenerationService",
    "DraftReviewError",
    "DraftReviewResult",
    "DraftReviewService",
    "FormalContextPlanError",
    "FormalContextPlanResult",
    "FormalContextPlanService",
    "FormalContextTaskQueueError",
    "FormalContextTaskQueueResult",
    "FormalContextTaskQueueService",
    "ManualRewriteTaskError",
    "ManualRewriteDraftSubmissionResult",
    "ManualRewriteComparisonDecisionResult",
    "ManualRewriteComparisonError",
    "ManualRewriteComparisonResult",
    "ManualRewriteComparisonService",
    "ManualRewriteTaskResult",
    "ManualRewriteTaskService",
    "ManualRewriteTaskStatusResult",
    "MemoryApplyPreviewError",
    "MemoryApplyPreviewResult",
    "MemoryApplyCommitResult",
    "MemoryApplyPreviewService",
    "MemoryBankError",
    "MemoryBankLifecycleResult",
    "MemoryBankService",
    "MemoryBankUpdateResult",
    "ReviewDecisionResult",
    "RevisionCandidateComparison",
    "RevisionCandidateError",
    "RevisionCandidateService",
    "RevisionCandidateSummary",
    "RevisionRequestError",
    "RevisionRequestResult",
    "RevisionRequestService",
    "fake_test_model_role",
    "generate_with_provider",
    "get_model_role_config",
    "list_provider_adapters",
    "provider_dry_run",
    "profile_corpus",
    "provider_real_test",
    "provider_status",
    "prepublish_check",
    "read_provider_call_log",
    "resolve_project_secret",
    "public_project_state",
    "set_real_generation_enabled",
    "set_project_secret",
    "set_model_role_config",
]
